name: Fetch AMI
description: Fetches the latest AMI using an artifact.

inputs:
  flavor:
    description: 'The flavor of the AMI to fetch.'
    required: true
  repo_pat:
    description: 'GitHub Personal Access Token with repo scope'
    required: true

outputs:
  ami_id:
    description: 'The ID of the fetched AMI.'
    value: ${{ steps.fetch_ami.outputs.ami_id }}

runs:
  using: "composite"
  steps:
    - name: Get latest successful run ID of skmahto101210/test_artifacts
      shell: bash
      id: get_run
      run: |
        response=$(curl -s -H "Authorization: token ${{ inputs.repo_pat }}" \
          "https://api.github.com/repos/skmahto101210/test_artifacts/actions/runs?status=success&per_page=1")
        
        run_id=$(echo "$response" | jq -r '.workflow_runs[0].id')
        echo "run_id=$run_id" >> $GITHUB_OUTPUT

    - name: Get artifacts metadata from latest run
      shell: bash
      id: get_artifact
      run: |
        curl -s -H "Authorization: token ${{ inputs.repo_pat }}" \
          "https://api.github.com/repos/skmahto101210/test_artifacts/actions/runs/${{ steps.get_run.outputs.run_id }}/artifacts" > artifacts.json

        artifact_id=$(jq '.artifacts[] | select(.name=="${{ inputs.flavor }}_ami-ids") | .id' artifacts.json)
        echo "artifact_id=$artifact_id" >> $GITHUB_OUTPUT

    - name: Download artifact '${{ inputs.flavor }}_ami-ids'
      shell: bash
      run: |
        mkdir -p extracted

        curl -L -H "Authorization: token ${{ inputs.repo_pat }}" \
          -o ${{ inputs.flavor }}_ami-ids.zip \
          "https://api.github.com/repos/skmahto101210/test_artifacts/actions/artifacts/${{ steps.get_artifact.outputs.artifact_id }}/zip"

        unzip -q ${{ inputs.flavor }}_ami-ids.zip -d extracted

    - name: Extract AMI ID from ${{ inputs.flavor }}_ami-ids.json
      id: fetch_ami
      shell: bash
      run: |
        echo "AMI ID from ${{ inputs.flavor }}_ami-ids.json:"
        jq -r '.["us-west-2"]' extracted/${{ inputs.flavor }}_ami-ids.json
        echo "ami_id=$(jq -r '.["us-west-2"]' extracted/${{ inputs.flavor }}_ami-ids.json)" >> $GITHUB_OUTPUT