name: Fetch AMI

on:
  push:
    branches: [ "main" ]

jobs:
  build-x:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fetch AMI
        id: fetch_ami
        uses: ./.github/actions/fetch-ami
        with:
          flavor: x

      - name: Output AMI ID
        shell: bash
        run: |
          echo "AMI ID: ${{ steps.fetch_ami.outputs.ami_id }}"

  build-y:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fetch AMI
        id: fetch_ami
        uses: ./.github/actions/fetch-ami
        with:
          flavor: y

      - name: Output AMI ID
        shell: bash
        run: |
          echo "AMI ID: ${{ steps.fetch_ami.outputs.ami_id }}"
  
  build-z:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fetch AMI
        id: fetch_ami
        uses: ./.github/actions/fetch-ami
        with:
          flavor: z

      - name: Output AMI ID
        shell: bash
        run: |
          echo "AMI ID: ${{ steps.fetch_ami.outputs.ami_id }}"
